# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weatherdata',
            fields=[
                ('unique_string', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('weather_country', models.CharField(max_length=200)),
                ('weather_type', models.CharField(max_length=200)),
                ('weather_year', models.IntegerField(default=0)),
                ('month_or_season', models.CharField(max_length=200)),
                ('weather_reading', models.FloatField(default=0)),
            ],
        ),
    ]
